import type { NextPage } from "next";
import Head from "next/head";

const AboutPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>OrgasmTracker | About</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
        <h2 className="text-lg font-bold uppercase tracking-wider text-white">
          About
        </h2>

        <div className="flex flex-col gap-4 text-white">
          <p>
            A web app for tracking your orgasms. In development, so for now just
            keep track of your &apos;gasms and build up a history. See some
            basic stats, share with others, and more features to cum!
          </p>
        </div>
      </div>
    </>
  );
};

export default AboutPage;
