name: Release

on:
  push:
    branches:
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - uses: changesets/action@v1
        with:
          version-script: bun run version-packages
          publish-script: bun run tag-release
          pr-title: Version packages
          commit-message: Version packages
